theme: jekyll-theme-dinky
title: Alan Vivona
description: syscall59
#logo: https://media-exp1.licdn.com/dms/image/C4E03AQFacNFultmoJg/profile-displayphoto-shrink_800_800/0?e=1603929600&v=beta&t=SUT-wJpHul3aVJF8bKr8EK9HUfqbmHBt4QxPnpb1D5c
show_downloads: false
google_analytics: UA-176613422-1
